wip

diff --git a/template/Makefile.j2 b/template/Makefile.j2
--- a/template/Makefile.j2
+++ b/template/Makefile.j2
@@ -13,10 +13,13 @@ TAG    := $(shell git rev-parse --short HEAD)
 OPERATOR_NAME := {[ operator.name }]
 VERSION := $(shell cargo metadata --format-version 1 | jq -r '.packages[] | select(.name=="stackable-${OPERATOR_NAME}") | .version')
 
-DOCKER_REPO := docker.stackable.tech
 ORGANIZATION := stackable
+OCI_REGISTRY_HOSTNAME := broadminded-goldstine.container-registry.com
+OCI_REGISTRY_PROJECT_IMAGES := ${ORGANIZATION}
+OCI_REGISTRY_PROJECT_CHARTS := ${OCI_REGISTRY_PROJECT_IMAGES}
 # this will be overwritten by an environmental variable if called from the github action
 HELM_REPO := https://repo.stackable.tech/repository/helm-dev
+HELM_CHART_NAME := ${OPERATOR_NAME}
 HELM_CHART_ARTIFACT := target/helm/${OPERATOR_NAME}-${VERSION}.tgz
 
 SHELL=/usr/bin/env bash -euo pipefail
@@ -26,11 +29,18 @@ render-readme:
 
 ## Docker related targets
 docker-build:
-	docker build --force-rm --build-arg VERSION=${VERSION} -t "${DOCKER_REPO}/${ORGANIZATION}/${OPERATOR_NAME}:${VERSION}" -f docker/Dockerfile .
+	docker build --force-rm --build-arg VERSION=${VERSION} -t '${OCI_REGISTRY_HOSTNAME}/${OCI_REGISTRY_PROJECT_IMAGES}/${OPERATOR_NAME}:${VERSION}' -f docker/Dockerfile .
 
 docker-publish:
-	echo "${NEXUS_PASSWORD}" | docker login --username github --password-stdin "${DOCKER_REPO}"
-	docker push --all-tags "${DOCKER_REPO}/${ORGANIZATION}/${OPERATOR_NAME}"
+	# we need to use "value" here to prevent the variable from being recursively expanded by make (username contains a dollar sign)
+	docker login --username '${value OCI_REGISTRY_USERNAME}' --password '${OCI_REGISTRY_PASSWORD}' '${OCI_REGISTRY_HOSTNAME}'
+	docker push --all-tags '${OCI_REGISTRY_HOSTNAME}/${ORGANIZATION}/${OPERATOR_NAME}'
+	REPO_ARTIFACT_BY_DIGEST=$$(docker inspect --format='{{range .RepoDigests}}{{ . }}{{end}}' '${OCI_REGISTRY_HOSTNAME}/${ORGANIZATION}/${OPERATOR_NAME}:${VERSION}' | grep -E '^${OCI_REGISTRY_HOSTNAME}/${ORGANIZATION}/${OPERATOR_NAME}@sha256:[0-9a-f]{64}$$' | head -n1);\
+	if [ -z "$$REPO_ARTIFACT_BY_DIGEST" ]; then\
+		echo 'Could not find repo digest for container image: ${OCI_REGISTRY_HOSTNAME}/${ORGANIZATION}/${OPERATOR_NAME}:${VERSION}';\
+		exit 1;\
+	fi;\
+	cosign sign -y $$REPO_ARTIFACT_BY_DIGEST
 
 # TODO remove if not used/needed
 docker: docker-build docker-publish
@@ -40,6 +50,14 @@ print-docker-tag:
 
 helm-publish:
 	curl --fail -u "github:${NEXUS_PASSWORD}" --upload-file "${HELM_CHART_ARTIFACT}" "${HELM_REPO}/"
+	# we need to use "value" here to prevent the variable from being recursively expanded by make (username contains a dollar sign)
+	helm registry login --username '${value OCI_REGISTRY_USERNAME}' --password '${OCI_REGISTRY_PASSWORD}' '${OCI_REGISTRY_HOSTNAME}'
+	REPO_ARTIFACT_BY_DIGEST=$$(helm push ${HELM_CHART_ARTIFACT} oci://${OCI_REGISTRY_HOSTNAME}/${OCI_REGISTRY_PROJECT_CHARTS} 2>&1 | awk '/^Digest: sha256:[0-9a-f]{64}$$/ { print $$2 }');\
+	if [ -z "$$REPO_ARTIFACT_BY_DIGEST" ]; then\
+		echo 'Could not find repo digest for helm chart: ${HELM_CHART_NAME}';\
+		exit 1;\
+	fi;\
+	cosign sign -y ${OCI_REGISTRY_HOSTNAME}/${OCI_REGISTRY_PROJECT_CHARTS}/${HELM_CHART_NAME}:@$$REPO_ARTIFACT_BY_DIGEST
 
 helm-package:
 	mkdir -p target/helm && helm package --destination target/helm deploy/helm/${OPERATOR_NAME}
@@ -70,7 +88,7 @@ chart-lint: compile-chart
 
 clean: chart-clean
 	cargo clean
-	docker rmi --force "${DOCKER_REPO}/${ORGANIZATION}/${OPERATOR_NAME}:${VERSION}"
+	docker rmi --force '${OCI_REGISTRY_HOSTNAME}/${OCI_REGISTRY_PROJECT_IMAGES}/${OPERATOR_NAME}:${VERSION}'
 
 regenerate-charts: chart-clean compile-chart
 
